# ===============================
# MySQL Database Settings
# ===============================
# ???URL (review_db ?Step1????DB?)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/review_db}

# ???????????
spring.datasource.username=root
# ???: ???Step1??????????????????
spring.datasource.password=TakatanRootpass1007&1

# ????????MySQL??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================
# ?????????????????????
spring.jpa.hibernate.ddl-auto=update

# ?????SQL???????????????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL?????SQL???????????
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT:8080}